### ISSUE TITLE
Plugin not working.

### ISSUE THREAD

**Issue by shivekkhurana** [recharts/babel-plugin-recharts#1]
Recharts is an amazing library but my build size is bloating up to 3.11mb.

I installed this using and added recharts to babel-loader plugins, but I get the following error (for every imported component)

`
ERROR in ./app/src/components/dashboard/elements/charts/Clicks.js
Module not found: Error: Cannot resolve module 'recharts/component/ResponsiveContainer' in /Users/shivekkhurana/Documents/WIP/Convfy/c
onvfy-frontend/app/src/components/dashboard/elements/charts
 @ ./app/src/components/dashboard/elements/charts/Clicks.js 37:27-76
`

How to go about this Sir ?

- "react": "^15.1.0",
- "react-dom": "^15.1.0",
- "recharts": "^0.12.3",

Thank you

**Comment by xile611** [comment]
@shivekkhurana  Can you describe your question in a simple project that we can have access to ?

**Comment by shivekkhurana** [comment]
I'm sorry for the delay. 

Please clone this repository. And `npm run build`. The error will be reproduced. 
https://github.com/shivekkhurana/recharts-babel-error-demo

Thank you.

**Comment by xile611** [comment]
@shivekkhurana Thank you for your demo.

You should tweak the following references: 
```
import XAxis from 'recharts/cartesian/XAxis';
import YAxis from 'recharts/cartesian/YAxis';
import CartesianGrid from 'recharts/cartesian/CartesianGrid';
import Area from 'recharts/cartesian/Area';
import AreaChart from 'recharts/chart/AreaChart';
import Tooltip from 'recharts/component/Tooltip';
import ResponsiveContainer from 'recharts/component/ResponsiveContainer';
```

to: 
```
import { XAxis, YAxis, CartesianGrid, Area, AreaChart, Tooltip,
  ResponsiveContainer } from 'recharts';
```

If you have used the *babel-plugin-recharts*,  the plugin will parse the references as following:

```
'use strict';

var _XAxis = require('recharts/lib/cartesian/XAxis');

var _XAxis2 = _interopRequireDefault(_XAxis);

var _YAxis = require('recharts/lib/cartesian/YAxis');

var _YAxis2 = _interopRequireDefault(_YAxis);

var _CartesianGrid = require('recharts/lib/cartesian/CartesianGrid');

var _CartesianGrid2 = _interopRequireDefault(_CartesianGrid);

var _Area = require('recharts/lib/cartesian/Area');

var _Area2 = _interopRequireDefault(_Area);

var _AreaChart = require('recharts/lib/chart/AreaChart');

var _AreaChart2 = _interopRequireDefault(_AreaChart);

var _Tooltip = require('recharts/lib/component/Tooltip');

var _Tooltip2 = _interopRequireDefault(_Tooltip);

var _ResponsiveContainer = require('recharts/lib/component/ResponsiveContainer');

var _ResponsiveContainer2 = _interopRequireDefault(_ResponsiveContainer);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

```

So the size of built file can be smaller.

![image](https://cloud.githubusercontent.com/assets/6111424/16905151/3a72f298-4cd4-11e6-808e-d47711fbb588.png)

![image](https://cloud.githubusercontent.com/assets/6111424/16905152/450ef544-4cd4-11e6-83d9-5ed0d02ada5a.png)

**Comment by shivekkhurana** [comment]
Beautiful. 

Thanks for your time. Recharts have helped  a lot.
