### ISSUE TITLE
TypeError: absPath.indexOf is not a function

### ISSUE THREAD

**Issue by bypeterhung** [recharts/babel-plugin-recharts#12]
ERROR in ./src/index.js  
Module build failed (from ./node_modules/_babel-loader@8.0.6@babel-loader/lib/index.js):  
TypeError: absPath.indexOf is not a function  
at findPath (E:\repo\data-ui\node_modules\_babel-plugin-recharts@1.2.0@babel-plugin-recharts\lib\index.js:75:100) ...

Received above error when I run my project with "recharts": "^2.0.0-beta.1" and "babel-plugin-recharts": "^1.2.0" installed. I end up getting it to work by tweak the following line (59) of \node_modules\_babel-plugin-recharts@1.2.0@babel-plugin-recharts\lib\index.js:

From

var fullPath = _path.default.resolve(rechartsSrcPath, source.indexOf('.js') >= 0 ? source : `${source}.js`);

To

var fullPath = _path.default.resolve(rechartsSrcPath, source.indexOf('.js') >= 0 ? source : `${source}.js`).replace('\\src\\', '\\lib\\');

Can't find anything about it online so far...

**Comment by semoal** [comment]
I guess this library with the v2.0.0 version is not necessary. Actually comes with treeshaking enabled.

**Comment by oziniak** [comment]
@bypeterhung have you figured anything out?

**Comment by bypeterhung** [comment]
@oziniak just like what @semoal said, that plug-in is not needed anymore when using v2, makes me wonder why it is still shown in the github page (https://github.com/recharts/recharts#module-formats) though ......

**Comment by gaurav5430** [comment]
is tree shaking enabled by default in v2?
I don't see any change in bundle size between:

`import { BarChart, Bar } from 'recharts';`

and 
`import { LineChart, Line } from 'recharts';`

I can see that all the components are included in both. I am using recharts 2.0.0-beta.6
