### ISSUE TITLE
Node.js 12.16.* - Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by MFoksik** [recharts/babel-plugin-recharts#13]
Hello,

after upgrading nodejs to 12.16.0 I get error from `babel-plugin-recharts`:

> TypeError: Cannot read property 'concat' of undefined
>     at findPath (PATH-TO-PROJECT/node_modules/babel-plugin-recharts/lib/index.js:55:26

https://github.com/recharts/babel-plugin-recharts/blob/master/src/index.js#L40

As I checked, `const path` is `undefined`.

**Comment by knro** [comment]
Can confirm, same issue here.

**Comment by eeerin** [comment]
Also confirming same issue.

**Comment by xlsdg** [comment]
Same issue here.

**Comment by KostinOlegA** [comment]
Having the same problem

**Comment by hamedov93** [comment]
I am having the same issue, it used to work before.

**Comment by KostinOlegA** [comment]
@arcthur Please, Can you see what the problem is?

**Comment by chenrui2014** [comment]
Having the same problem

**Comment by bitpod-io** [comment]
A PR is pending approval to fix this. Can a maintainer please merge it?

**Comment by roman-veryovkin** [comment]
Please merge the PR to fix this.

**Comment by arcthur** [comment]
ok，i will merge today
