### ISSUE TITLE
After upgraded Recharts to v2.0.2, cannot run the project

### ISSUE THREAD

**Issue by Bnacha** [recharts/babel-plugin-recharts#20]
I have upgraded Recharts from v1.8.5 to v2.0.2 but got this error when start my project

![image](https://user-images.githubusercontent.com/35885558/104535925-a376b800-5649-11eb-9a44-01708ff53793.png)

If I remove ["recharts"] from .babelrc it works but I will lose the ability of babel-plugin-recharts

Recharts v2.0.2
babel-plugin-recharts v1.2.1

**Comment by nicholaschiang** [comment]
Yup, the new Recharts version seems to be using TypeScript (i.e. `index.ts`) instead of JavaScript for that `index.js` file. I can recreate this issue too and it'd be nice to have a fix @arcthur!
