### ISSUE TITLE
Babel@7 support

### ISSUE THREAD

**Issue by Akurganow** [recharts/babel-plugin-recharts#8]
Please dd support for babel@7 and babel-loader@8
https://babeljs.io/docs/en/v7-migration

**Comment by arcthur** [comment]
OK

**Comment by annilq** [comment]
I also meet some problem with this plugin ,can sombody tell me how to solve it? many thanks
```
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.3",
    "babel-plugin-import": "^1.8.0",
    "babel-plugin-recharts": "^1.2.0",

```
<img width="875" alt="wx20190106-192955 2x" src="https://user-images.githubusercontent.com/6497194/50735405-881a7c00-11e9-11e9-87de-275edc62e2f8.png">

**Comment by arcthur** [comment]
babel-core will update to @babel/core ^7

**Comment by annilq** [comment]
> babel-core will update to @babel/core ^7

sorry for reply so late,I don't realize I have  notifications ,I have upgrade this plugin and it works,thanks
